// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package rmi;

public final class HelloImp_Stub
    extends java.rmi.server.RemoteStub
    implements rmi.Hello, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_disName_0;
    
    static {
	try {
	    $method_disName_0 = rmi.Hello.class.getMethod("disName", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public HelloImp_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of disName()
    public java.lang.String disName()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_disName_0, null, -7698466215965952905L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
